<?php
return array(
    1 => array(
       // 'slug' => \MapasCulturais\i::__('tag'),
    'slug' => 'tag',
        'entities' => array(
            'MapasCulturais\Entities\Space',
            'MapasCulturais\Entities\Agent',
            'MapasCulturais\Entities\Event',
            'MapasCulturais\Entities\Project',
            'MapasCulturais\Entities\Opportunity',
        )
    ),

    2 => array(
        //'slug' => \MapasCulturais\i::__('area'),
        'slug' => 'area',
        'required' => \MapasCulturais\i::__("Você deve informar ao menos uma área de atuação"),
        'entities' => array(
            'MapasCulturais\Entities\Space',
            'MapasCulturais\Entities\Agent'
        ),
        // SELECT DISTINCT cbo_descricao FROM cnes.elastic_sagu_cnes_egressos WHERE cbo_descricao <> '' ORDER BY cbo_descricao
        'restricted_terms' => array(
            \MapasCulturais\i::__("ADMINISTRADOR"),
            \MapasCulturais\i::__("ADMINISTRADOR DE BANCO DE DADOS"),
            \MapasCulturais\i::__("ADMINISTRADOR DE SISTEMAS OPERACIONAIS"),
            \MapasCulturais\i::__("AGENTE COMUNITARIO DE SAUDE"),
            \MapasCulturais\i::__("AGENTE DE COMBATE AS ENDEMIAS"),
            \MapasCulturais\i::__("AGENTE DE SAUDE PUBLICA"),
            \MapasCulturais\i::__("AGENTE INDIGENA DE SANEAMENTO"),
            \MapasCulturais\i::__("AGENTE INDIGENA DE SAUDE"),
            \MapasCulturais\i::__("ANALISTA DE INFORMACOES (PESQUISADOR DE INFORMACOES DE REDE)"),
            \MapasCulturais\i::__("ARTESAO COM MATERIAL RECICLAVEL"),
            \MapasCulturais\i::__("ASSISTENTE ADMINISTRATIVO"),
            \MapasCulturais\i::__("ASSISTENTE SOCIAL"),
            \MapasCulturais\i::__("ATENDENTE DE ENFERMAGEM"),
            \MapasCulturais\i::__("ATENDENTE DE FARMACIA  BALCONISTA"),
            \MapasCulturais\i::__("AUDITOR (CONTADORES E AFINS)"),
            \MapasCulturais\i::__("AUXILIAR DE ENFERMAGEM"),
            \MapasCulturais\i::__("AUXILIAR DE ENFERMAGEM DA ESTRATEGIA DE SAUDE DA FAMILIA"),
            \MapasCulturais\i::__("AUXILIAR DE ESCRITORIO, EM GERAL"),
            \MapasCulturais\i::__("AUXILIAR DE FARMACIA DE MANIPULACAO"),
            \MapasCulturais\i::__("AUXILIAR DE LABORATORIO DE ANALISES CLINICAS"),
            \MapasCulturais\i::__("AUXILIAR DE PRODUCAO FARMACEUTICA"),
            \MapasCulturais\i::__("AUXILIAR DE VETERINARIO"),
            \MapasCulturais\i::__("AUXILIAR EM SAUDE BUCAL"),
            \MapasCulturais\i::__("AUXILIAR EM SAUDE BUCAL DA ESTRATEGIA DE SAUDE DA FAMILIA"),
            \MapasCulturais\i::__("AUXILIAR TECNICO EM LABORATORIO DE FARMACIA"),
            \MapasCulturais\i::__("AUXILIAR TECNICO EM PATOLOGIA CLINICA"),
            \MapasCulturais\i::__("AVALIADOR FISICO"),
            \MapasCulturais\i::__("BIOLOGO"),
            \MapasCulturais\i::__("BIOMEDICO"),
            \MapasCulturais\i::__("CIRURGIAO DENTISTA  CLINICO GERAL"),
            \MapasCulturais\i::__("CIRURGIAODENTISTA DA ESTRATEGIA DE SAUDE DA FAMILIA"),
            \MapasCulturais\i::__("CIRURGIAO DENTISTA  DENTISTICA"),
            \MapasCulturais\i::__("CIRURGIAO DENTISTA DE SAUDE COLETIVA"),
            \MapasCulturais\i::__("CIRURGIAO DENTISTA  ENDODONTISTA"),
            \MapasCulturais\i::__("CIRURGIAO DENTISTA  ODONTOLOGIA PARA PACIENTES COM NECESSIDADES ESPECIAIS"),
            \MapasCulturais\i::__("CIRURGIAO DENTISTA  ODONTOLOGISTA LEGAL"),
            \MapasCulturais\i::__("CIRURGIAO DENTISTA  ODONTOPEDIATRA"),
            \MapasCulturais\i::__("CIRURGIAO DENTISTA  ORTOPEDISTA E ORTODONTISTA"),
            \MapasCulturais\i::__("CIRURGIAO DENTISTA  PERIODONTISTA"),
            \MapasCulturais\i::__("CIRURGIAO DENTISTA  PROTESISTA"),
            \MapasCulturais\i::__("CIRURGIAO DENTISTA  RADIOLOGISTA"),
            \MapasCulturais\i::__("CIRURGIAO DENTISTA  TRAUMATOLOGISTA BUCOMAXILOFACIAL"),
            \MapasCulturais\i::__("CONDUTOR DE AMBULANCIA"),
            \MapasCulturais\i::__("CONTROLADOR DE PRAGAS"),
            \MapasCulturais\i::__("DIGITADOR"),
            \MapasCulturais\i::__("DIRETOR ADMINISTRATIVO"),
            \MapasCulturais\i::__("DIRETOR ADMINISTRATIVO E FINANCEIRO"),
            \MapasCulturais\i::__("DIRETOR DE PLANEJAMENTO ESTRATEGICO"),
            \MapasCulturais\i::__("DIRETOR DE SERVICOS DE SAUDE"),
            \MapasCulturais\i::__("DIRIGENTE DO SERVICO PUBLICO MUNICIPAL"),
            \MapasCulturais\i::__("ECONOMISTA DOMESTICO"),
            \MapasCulturais\i::__("EDUCADOR SOCIAL"),
            \MapasCulturais\i::__("EMPREGADO DOMESTICO NOS SERVICOS GERAIS"),
            \MapasCulturais\i::__("ENFERMEIRO"),
            \MapasCulturais\i::__("ENFERMEIRO AUDITOR"),
            \MapasCulturais\i::__("ENFERMEIRO DA ESTRATEGIA DE SAUDE DA FAMILIA"),
            \MapasCulturais\i::__("ENFERMEIRO DE CENTRO CIRURGICO"),
            \MapasCulturais\i::__("ENFERMEIRO DE TERAPIA INTENSIVA"),
            \MapasCulturais\i::__("ENFERMEIRO DO TRABALHO"),
            \MapasCulturais\i::__("ENFERMEIRO NEFROLOGISTA"),
            \MapasCulturais\i::__("ENFERMEIRO NEONATOLOGISTA"),
            \MapasCulturais\i::__("ENFERMEIRO OBSTETRICO"),
            \MapasCulturais\i::__("ENFERMEIRO PSIQUIATRICO"),
            \MapasCulturais\i::__("ENFERMEIRO PUERICULTOR E PEDIATRICO"),
            \MapasCulturais\i::__("ENFERMEIRO SANITARISTA"),
            \MapasCulturais\i::__("ESPECIALISTA DE POLITICAS PUBLICAS E GESTAO GOVERNAMENTAL  EPPGG"),
            \MapasCulturais\i::__("ESTATISTICO"),
            \MapasCulturais\i::__("FARMACEUTICO"),
            \MapasCulturais\i::__("FARMACEUTICO ANALISTA CLINICO"),
            \MapasCulturais\i::__("FARMACEUTICO HOSPITALAR E CLINICO"),
            \MapasCulturais\i::__("FAXINEIRO"),
            \MapasCulturais\i::__("FISIOTERAPEUTA ACUPUNTURISTA"),
            \MapasCulturais\i::__("FISIOTERAPEUTA GERAL"),
            \MapasCulturais\i::__("FISIOTERAPEUTA NEUROFUNCIONAL"),
            \MapasCulturais\i::__("FONOAUDIOLOGO"),
            \MapasCulturais\i::__("GERENTE ADMINISTRATIVO"),
            \MapasCulturais\i::__("GERENTE DE PRODUCAO DE TECNOLOGIA DA INFORMACAO"),
            \MapasCulturais\i::__("GERENTE DE SERVICOS DE SAUDE"),
            \MapasCulturais\i::__("GERENTE DE SUPORTE TECNICO DE TECNOLOGIA DA INFORMACAO"),
            \MapasCulturais\i::__("GESSEIRO"),
            \MapasCulturais\i::__("GUARDACIVIL MUNICIPAL"),
            \MapasCulturais\i::__("MEDICO ACUPUNTURISTA"),
            \MapasCulturais\i::__("MEDICO ANESTESIOLOGISTA"),
            \MapasCulturais\i::__("MEDICO CARDIOLOGISTA"),
            \MapasCulturais\i::__("MEDICO CIRURGIAO GERAL"),
            \MapasCulturais\i::__("MEDICO CITOPATOLOGISTA"),
            \MapasCulturais\i::__("MEDICO CLINICO"),
            \MapasCulturais\i::__("MEDICO COLOPROCTOLOGISTA"),
            \MapasCulturais\i::__("MEDICO DA ESTRATEGIA DE SAUDE DA FAMILIA"),
            \MapasCulturais\i::__("MEDICO DERMATOLOGISTA"),
            \MapasCulturais\i::__("MEDICO DO TRABALHO"),
            \MapasCulturais\i::__("MEDICO EM CIRURGIA VASCULAR"),
            \MapasCulturais\i::__("MEDICO EM ENDOSCOPIA"),
            \MapasCulturais\i::__("MEDICO EM MEDICINA INTENSIVA"),
            \MapasCulturais\i::__("MEDICO EM RADIOLOGIA E DIAGNOSTICO POR IMAGEM"),
            \MapasCulturais\i::__("MEDICO ENDOCRINOLOGISTA E METABOLOGISTA"),
            \MapasCulturais\i::__("MEDICO GENERALISTA"),
            \MapasCulturais\i::__("MEDICO GENETICISTA"),
            \MapasCulturais\i::__("MEDICO GERIATRA"),
            \MapasCulturais\i::__("MEDICO GINECOLOGISTA E OBSTETRA"),
            \MapasCulturais\i::__("MEDICO HEMATOLOGISTA"),
            \MapasCulturais\i::__("MEDICO INFECTOLOGISTA"),
            \MapasCulturais\i::__("MEDICO NEUROCIRURGIAO"),
            \MapasCulturais\i::__("MEDICO NEUROLOGISTA"),
            \MapasCulturais\i::__("MEDICO ONCOLOGISTA CLINICO"),
            \MapasCulturais\i::__("MEDICO ORTOPEDISTA E TRAUMATOLOGISTA"),
            \MapasCulturais\i::__("MEDICO PATOLOGISTA"),
            \MapasCulturais\i::__("MEDICO PEDIATRA"),
            \MapasCulturais\i::__("MEDICO PNEUMOLOGISTA"),
            \MapasCulturais\i::__("MEDICO PSIQUIATRA"),
            \MapasCulturais\i::__("MEDICO REUMATOLOGISTA"),
            \MapasCulturais\i::__("MEDICO VETERINARIO"),
            \MapasCulturais\i::__("MOTORISTA DE CARRO DE PASSEIO"),
            \MapasCulturais\i::__("MOTORISTA DE FURGAO OU VEICULO SIMILAR"),
            \MapasCulturais\i::__("NUTRICIONISTA"),
            \MapasCulturais\i::__("OPERADOR DE COMPUTADOR (INCLUSIVE MICROCOMPUTADOR)"),
            \MapasCulturais\i::__("OPERADOR DE RADIOCHAMADA"),
            \MapasCulturais\i::__("OUVIDOR"),
            \MapasCulturais\i::__("PARTEIRA LEIGA"),
            \MapasCulturais\i::__("PEDAGOGO"),
            \MapasCulturais\i::__("PSICOLOGO CLINICO"),
            \MapasCulturais\i::__("PSICOLOGO HOSPITALAR"),
            \MapasCulturais\i::__("PSICOLOGO SOCIAL"),
            \MapasCulturais\i::__("PSICOPEDAGOGO"),
            \MapasCulturais\i::__("RECEPCIONISTA DE CONSULTORIO MEDICO OU DENTARIO"),
            \MapasCulturais\i::__("RECEPCIONISTA, EM GERAL"),
            \MapasCulturais\i::__("SECRETARIA EXECUTIVA"),
            \MapasCulturais\i::__("SECRETARIOEXECUTIVO"),
            \MapasCulturais\i::__("SOCIOLOGO"),
            \MapasCulturais\i::__("SOCORRISTA (EXCETO MEDICOS E ENFERMEIROS)"),
            \MapasCulturais\i::__("SUPERVISOR ADMINISTRATIVO"),
            \MapasCulturais\i::__("TECNICO DE ALIMENTOS"),
            \MapasCulturais\i::__("TECNICO DE APOIO AO USUARIO DE INFORMATICA (HELPDESK)"),
            \MapasCulturais\i::__("TECNICO DE ENFERMAGEM"),
            \MapasCulturais\i::__("TECNICO DE ENFERMAGEM DA ESTRATEGIA DE SAUDE DA FAMILIA"),
            \MapasCulturais\i::__("TECNICO DE ENFERMAGEM DO TRABALHO"),
            \MapasCulturais\i::__("TECNICO DE ENFERMAGEM PSIQUIATRICA"),
            \MapasCulturais\i::__("TECNICO DE GARANTIA DA QUALIDADE"),
            \MapasCulturais\i::__("TECNICO DE IMOBILIZACAO ORTOPEDICA"),
            \MapasCulturais\i::__("TECNICO DE OBRAS CIVIS"),
            \MapasCulturais\i::__("TECNICO DE SANEAMENTO"),
            \MapasCulturais\i::__("TECNICO EM ADMINISTRACAO"),
            \MapasCulturais\i::__("TECNICO EM LABORATORIO DE FARMACIA"),
            \MapasCulturais\i::__("TECNICO EM METODOS ELETROGRAFICOS EM ENCEFALOGRAFIA"),
            \MapasCulturais\i::__("TECNICO EM PATOLOGIA CLINICA"),
            \MapasCulturais\i::__("TECNICO EM RADIOLOGIA E IMAGENOLOGIA"),
            \MapasCulturais\i::__("TECNICO EM SAUDE BUCAL"),
            \MapasCulturais\i::__("TECNICO EM SAUDE BUCAL DA ESTRATEGIA DE SAUDE DA FAMILIA"),
            \MapasCulturais\i::__("TECNICO EM SEGURANCA NO TRABALHO"),
            \MapasCulturais\i::__("TECNOLOGO EM ALIMENTOS"),
            \MapasCulturais\i::__("TECNOLOGO EM GESTAO HOSPITALAR"),
            \MapasCulturais\i::__("TECNOLOGO EM MEIO AMBIENTE"),
            \MapasCulturais\i::__("TECNOLOGO EM RADIOLOGIA"),
            \MapasCulturais\i::__("TELEFONISTA"),
            \MapasCulturais\i::__("TERAPEUTA OCUPACIONAL"),
            \MapasCulturais\i::__("TRABALHADOR DE SERVICOS DE LIMPEZA E CONSERVACAO DE AREAS PUBLICAS"),
            \MapasCulturais\i::__("VISITADOR SANITARIO"),
            \MapasCulturais\i::__("OUTROS"),
        )
    ),

    3 => array(
        'slug' => 'linguagem',
        'required' => \MapasCulturais\i::__("Você deve informar ao menos uma linguagem"),
        'entities' => array(
            'MapasCulturais\Entities\Event'
        ),

        'restricted_terms' => array(
        )
    )
);
